Add trezor firmware warning
vacuumlabs/adalite pull request #1039
Opened 2021-06-14 12:32 UTC by DavidTranDucVL

2021-06-15 10:04 UTC, refi93 commented
I'd add some text next to the warning sign, like "Known issue" to give some more context to the user before reading the longer text of the pop-up. Arguably, it could be just a link which would take users to our wiki page with a more structured text

2021-06-15 20:25 UTC, refi93 requested changes
see comment

2021-06-21 11:49 UTC, DavidTranDucVL commented
@refi93 please recheck

2021-06-22 10:35 UTC, refi93 commented on app/frontend/components/pages/login/hardwareAuth.tsx
> +            <a href="https://github.com/vacuumlabs/adalite/wiki/Troubleshooting#blank-phrase-on-trezor-login-issue">
please make it target _blank so that a new tab opens instead of abandoning the Adalite site

2021-06-22 10:36 UTC, refi93 approved these changes
One suggestion regarding the link, otherwise LGTM

2021-06-22 12:22 UTC, merged