Bulk export gradually more public keys
vacuumlabs/adalite pull request #984
Opened 2021-05-10 10:10 UTC by PeterBenc

Motivation: 
 - for wallets that have a lot of account ist more convenient to export public key by batches bigger than 5

Changes: 
 - public keys are exported in batches of 5, 10, 20, 20.... (from 20 the batch stays the same, exporting more than 20 key from ledger takes a bit too long)

2021-05-10 16:24 UTC, refi93 commented on app/frontend/wallet/helpers/CachedDeriveXpubFactory.ts
> +    const nAccounts = Math.min(currentAccountPage + 1, 3) * MAX_BULK_EXPORT_AMOUNT
This is getting really misleading - MAX_BULK_EXPORT_AMOUNT is not the maximum number of exported public keys anymore and the "current page" is not really the "current page" as these are now of variable size and not really "pages" as units of exported data.

I'd consider renaming the `MAX_BULK_EXPORT_AMOUNT` constant to `EXPORTED_PATHS_SLICE_SIZE`, `currentAccountPage` to `currentAccountSlice`, and to get the `nAccounts` I'd rather make a helper function `getExportedBulkSize` which would take as an argument the currentAccountSlice and have explicit `if-else` for returning the bulk size than a rather cryptic, albeit short formula

2021-05-10 16:25 UTC, refi93 requested changes
see comment

2021-05-10 17:03 UTC, PeterBenc commented on app/frontend/wallet/constants.ts
> +export const MAX_ACCOUNT_INDEX = 29
Changed this to 29 since exporting 30 accounts means exporting up to index 29.

2021-05-19 22:12 UTC, refi93 commented on app/frontend/wallet/constants.ts
> +export const MAX_ACCOUNT_INDEX = 34
why did we have to bump this? I'd rather stay at 30 if we don't have a strong reason to bump it, 34 seems really arbitrary

2021-05-19 22:14 UTC, refi93 approved these changes
overall LGTM, just one question regarding MAX_ACCOUNT_INDEX

2021-05-20 08:06 UTC, merged